"""
Creates the SQLite database schema for the photo/video indexing project.

Tables:
  files    - one row per unique file (photo or video), standard + AI metadata
  tags     - object/color/scene/activity tags generated by the vision model
  faces    - individual face detections (with embeddings) found in files
  clusters - groups of faces believed to be the same person, with a label

Design notes:
  - content_hash is the stable identity of a file. file_path can change
    (if you reorganize folders) without triggering reprocessing, since we
    match on hash first.
  - Videos are handled by extracting representative frames; tags and faces
    both carry an optional frame_timestamp so we know which moment in the
    video they came from. This is NULL for photos.
  - *_processed_at timestamps let the indexing pipeline resume cleanly:
    if a file has metadata_extracted_at set but tags_processed_at is NULL,
    we know exactly which step to run next.
"""

import sqlite3
from pathlib import Path

DB_PATH = Path("/mnt/storage_sata/photo_index.db")

SCHEMA = """
CREATE TABLE IF NOT EXISTS files (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_path TEXT NOT NULL UNIQUE,
    content_hash TEXT NOT NULL UNIQUE,
    media_type TEXT NOT NULL CHECK (media_type IN ('photo', 'video')),
    file_size_bytes INTEGER,

    date_taken TEXT,
    date_source TEXT,
    gps_lat REAL,
    gps_lon REAL,
    camera_make TEXT,
    camera_model TEXT,

    caption TEXT,

    metadata_extracted_at TIMESTAMP,
    faces_processed_at TIMESTAMP,
    tags_processed_at TIMESTAMP,

    is_missing INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_files_content_hash ON files(content_hash);
CREATE INDEX IF NOT EXISTS idx_files_date_taken ON files(date_taken);
CREATE INDEX IF NOT EXISTS idx_files_metadata_pending ON files(metadata_extracted_at);
CREATE INDEX IF NOT EXISTS idx_files_faces_pending ON files(faces_processed_at);
CREATE INDEX IF NOT EXISTS idx_files_tags_pending ON files(tags_processed_at);

CREATE TABLE IF NOT EXISTS tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_id INTEGER NOT NULL REFERENCES files(id) ON DELETE CASCADE,
    tag_text TEXT NOT NULL,
    category TEXT CHECK (category IN ('object', 'color', 'scene', 'activity')),
    frame_timestamp REAL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tags_file_id ON tags(file_id);
CREATE INDEX IF NOT EXISTS idx_tags_text ON tags(tag_text);

CREATE TABLE IF NOT EXISTS clusters (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    person_name TEXT,
    representative_embedding BLOB,
    face_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_clusters_person_name ON clusters(person_name);

CREATE TABLE IF NOT EXISTS faces (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_id INTEGER NOT NULL REFERENCES files(id) ON DELETE CASCADE,
    cluster_id INTEGER REFERENCES clusters(id) ON DELETE SET NULL,
    embedding BLOB NOT NULL,
    bbox_x REAL,
    bbox_y REAL,
    bbox_width REAL,
    bbox_height REAL,
    frame_timestamp REAL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_faces_file_id ON faces(file_id);
CREATE INDEX IF NOT EXISTS idx_faces_cluster_id ON faces(cluster_id);
"""


def main():
    print(f"Creating database at: {DB_PATH}")
    conn = sqlite3.connect(DB_PATH)
    conn.executescript(SCHEMA)
    conn.commit()

    cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
    tables = [row[0] for row in cursor.fetchall()]

    print("\nTables created successfully:")
    for t in tables:
        print(f"  - {t}")

    conn.close()
    print(f"\nDatabase ready at {DB_PATH}")


if __name__ == "__main__":
    main()
